version: '3.1'

services:
  app:
    image: '2d01069991a53a388cafc2dc4bb6a57493d2d028496300a6572d9600d6992a21'
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_HOST=${SPRING_DATASOURCE_HOST}
      - SPRING_DATASOURCE_PORT=${SPRING_DATASOURCE_PORT}
      - SPRING_DATASOURCE_DATABASE=${SPRING_DATASOURCE_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SECURITY_PASSWORD_SECRET=${SECURITY_PASSWORD_SECRET}
      - SECURITY_PASSWORD_ITERATION=${SECURITY_PASSWORD_ITERATION}
      - SECURITY_PASSWORD_KEY_LENGTH=${SECURITY_PASSWORD_KEY_LENGTH}
      - JWT_SECRET_KEY_ACCESS=${JWT_SECRET_KEY_ACCESS}
      - JWT_SECRET_KEY_REFRESH=${JWT_SECRET_KEY_REFRESH}
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: db
    expose:
      - '5434'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password